// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddProxy(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Proxy>;

export function CancelTask(arg1:string):Promise<void>;

export function CreateBatch(arg1:Array<models.BatchTaskInput>,arg2:boolean):Promise<Array<models.Task>>;

export function CreateBatchFromFlow(arg1:models.AdvancedBatchInput):Promise<models.BatchGroup>;

export function CreateRecordedFlow(arg1:string,arg2:string,arg3:string,arg4:Array<models.RecordedStep>):Promise<models.RecordedFlow>;

export function CreateTask(arg1:string,arg2:string,arg3:Array<models.TaskStep>,arg4:models.ProxyConfig,arg5:number,arg6:boolean,arg7:Array<string>,arg8:number,arg9:models.TaskLoggingPolicy | null):Promise<models.Task>;

export function CreateTaskFromFlow(arg1:string,arg2:string,arg3:string,arg4:models.ProxyConfig,arg5:number,arg6:boolean,arg7:Array<string>):Promise<models.Task>;

export function DeleteProxy(arg1:string):Promise<void>;

export function DeleteRecordedFlow(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function ExportBatchLogs(arg1:string):Promise<string>;

export function ExportResultsCSV():Promise<string>;

export function ExportResultsJSON():Promise<string>;

export function ExportTaskLogs(arg1:string):Promise<string>;

export function GetAuditTrail(arg1:string,arg2:number):Promise<Array<models.TaskLifecycleEvent>>;

export function GetBatchProgress(arg1:string):Promise<models.BatchProgress>;

export function GetQueueMetrics():Promise<models.QueueMetrics>;

export function GetRecordedFlow(arg1:string):Promise<models.RecordedFlow>;

export function GetRunningCount():Promise<number>;

export function GetTask(arg1:string):Promise<models.Task>;

export function GetTaskStats():Promise<Record<string, number>>;

export function IsRecording():Promise<boolean>;

export function ListBatchGroups():Promise<Array<models.BatchGroup>>;

export function ListDOMSnapshots(arg1:string):Promise<Array<models.DOMSnapshot>>;

export function ListProxies():Promise<Array<models.Proxy>>;

export function ListProxyCountryStats():Promise<Array<models.ProxyCountryStats>>;
export function CreateProxyRoutingPreset(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<models.ProxyRoutingPreset>;
export function ListProxyRoutingPresets():Promise<Array<models.ProxyRoutingPreset>>;
export function DeleteProxyRoutingPreset(arg1:string):Promise<void>;
export function GetLocalProxyGatewayStats():Promise<models.LocalProxyGatewayStats>;

export function ListRecordedFlows():Promise<Array<models.RecordedFlow>>;

export function ListTaskEvents(arg1:string):Promise<Array<models.TaskLifecycleEvent>>;

export function ListTasks():Promise<Array<models.Task>>;

export function ListTasksByBatch(arg1:string):Promise<Array<models.Task>>;

export function ListTasksByStatus(arg1:string):Promise<Array<models.Task>>;

export function ListTasksPaginated(arg1:number,arg2:number,arg3:string,arg4:string):Promise<models.PaginatedTasks>;

export function ListWebSocketLogs(arg1:string):Promise<Array<models.WebSocketLog>>;

export function ParseBatchURLs(arg1:string,arg2:boolean):Promise<Array<string>>;

export function PlayRecordedFlow(arg1:string,arg2:string,arg3:boolean):Promise<models.Task>;

export function PurgeOldData(arg1:number):Promise<number>;

export function RetryFailedBatch(arg1:string):Promise<Array<models.Task>>;

export function SaveDOMSnapshot(arg1:models.DOMSnapshot):Promise<void>;

export function StartAllPending():Promise<void>;

export function StartRecording(arg1:string):Promise<void>;

export function StartTask(arg1:string):Promise<void>;

export function StopRecording():Promise<Array<models.RecordedStep>>;

export function UpdateRecordedFlow(arg1:models.RecordedFlow):Promise<void>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:Array<models.TaskStep>,arg5:models.ProxyConfig,arg6:number,arg7:Array<string>,arg8:number,arg9:models.TaskLoggingPolicy | null):Promise<void>;

export function CreateSchedule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:models.ProxyConfig,arg6:number,arg7:boolean,arg8:Array<string>):Promise<models.Schedule>;

export function GetSchedule(arg1:string):Promise<models.Schedule>;

export function ListSchedules():Promise<Array<models.Schedule>>;

export function UpdateSchedule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:models.ProxyConfig,arg7:number,arg8:boolean,arg9:Array<string>,arg10:boolean):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function ToggleSchedule(arg1:string,arg2:boolean):Promise<void>;

export function SaveCaptchaConfig(arg1:string,arg2:string):Promise<models.CaptchaConfig>;

export function GetCaptchaConfig():Promise<models.CaptchaConfig>;

export function ListCaptchaConfigs():Promise<Array<models.CaptchaConfig>>;

export function DeleteCaptchaConfig(arg1:string):Promise<void>;

export function TestCaptchaConfig(arg1:string):Promise<number>;

export function CreateVisualBaseline(arg1:string,arg2:string,arg3:string):Promise<models.VisualBaseline>;

export function ListVisualBaselines():Promise<Array<models.VisualBaseline>>;

export function DeleteVisualBaseline(arg1:string):Promise<void>;

export function CompareVisual(arg1:models.DiffRequest):Promise<models.VisualDiff>;

export function ListVisualDiffs(arg1:string):Promise<Array<models.VisualDiff>>;

export function ListVisualDiffsByTask(arg1:string):Promise<Array<models.VisualDiff>>;

export function GetVisualDiff(arg1:string):Promise<models.VisualDiff>;

export function PauseBatch(arg1:string):Promise<void>;

export function ResumeBatch(arg1:string):Promise<void>;
