// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddProxy'](arg1, arg2, arg3, arg4, arg5);
}

export function AddProxyWithRateLimit(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddProxyWithRateLimit'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CompareVisual(arg1) {
  return window['go']['main']['App']['CompareVisual'](arg1);
}

export function CreateAlertRule(arg1) {
  return window['go']['main']['App']['CreateAlertRule'](arg1);
}

export function CreateBatch(arg1, arg2) {
  return window['go']['main']['App']['CreateBatch'](arg1, arg2);
}

export function CreateBatchFromFlow(arg1) {
  return window['go']['main']['App']['CreateBatchFromFlow'](arg1);
}

export function CreateProxyRoutingPreset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProxyRoutingPreset'](arg1, arg2, arg3, arg4);
}

export function CreateRecordedFlow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRecordedFlow'](arg1, arg2, arg3, arg4);
}

export function CreateRepeatedTask(arg1) {
  return window['go']['main']['App']['CreateRepeatedTask'](arg1);
}

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTaskFromFlow(arg1) {
  return window['go']['main']['App']['CreateTaskFromFlow'](arg1);
}

export function CreateVisualBaseline(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVisualBaseline'](arg1, arg2, arg3);
}

export function DeleteAlertRule(arg1) {
  return window['go']['main']['App']['DeleteAlertRule'](arg1);
}

export function DeleteCaptchaConfig(arg1) {
  return window['go']['main']['App']['DeleteCaptchaConfig'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function DeleteProxyRoutingPreset(arg1) {
  return window['go']['main']['App']['DeleteProxyRoutingPreset'](arg1);
}

export function DeleteRecordedFlow(arg1) {
  return window['go']['main']['App']['DeleteRecordedFlow'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteVisualBaseline(arg1) {
  return window['go']['main']['App']['DeleteVisualBaseline'](arg1);
}

export function ExportBatchLogs(arg1) {
  return window['go']['main']['App']['ExportBatchLogs'](arg1);
}

export function ExportFlow(arg1) {
  return window['go']['main']['App']['ExportFlow'](arg1);
}

export function ExportResultsCSV() {
  return window['go']['main']['App']['ExportResultsCSV']();
}

export function ExportResultsJSON() {
  return window['go']['main']['App']['ExportResultsJSON']();
}

export function ExportTask(arg1) {
  return window['go']['main']['App']['ExportTask'](arg1);
}

export function ExportTaskLogs(arg1) {
  return window['go']['main']['App']['ExportTaskLogs'](arg1);
}

export function GetActiveAlerts() {
  return window['go']['main']['App']['GetActiveAlerts']();
}

export function GetAlertRule(arg1) {
  return window['go']['main']['App']['GetAlertRule'](arg1);
}

export function GetAuditTrail(arg1, arg2) {
  return window['go']['main']['App']['GetAuditTrail'](arg1, arg2);
}

export function GetBatchProgress(arg1) {
  return window['go']['main']['App']['GetBatchProgress'](arg1);
}

export function GetCaptchaConfig() {
  return window['go']['main']['App']['GetCaptchaConfig']();
}

export function GetEnhancedPrometheusMetrics() {
  return window['go']['main']['App']['GetEnhancedPrometheusMetrics']();
}

export function GetLocalProxyGatewayStats() {
  return window['go']['main']['App']['GetLocalProxyGatewayStats']();
}

export function GetLogStats() {
  return window['go']['main']['App']['GetLogStats']();
}

export function GetLogsByBatchID(arg1, arg2) {
  return window['go']['main']['App']['GetLogsByBatchID'](arg1, arg2);
}

export function GetLogsByLevel(arg1, arg2) {
  return window['go']['main']['App']['GetLogsByLevel'](arg1, arg2);
}

export function GetLogsByTaskID(arg1, arg2) {
  return window['go']['main']['App']['GetLogsByTaskID'](arg1, arg2);
}

export function GetMonitoringMetrics() {
  return window['go']['main']['App']['GetMonitoringMetrics']();
}

export function GetPrometheusMetrics() {
  return window['go']['main']['App']['GetPrometheusMetrics']();
}

export function GetQueueMetrics() {
  return window['go']['main']['App']['GetQueueMetrics']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetRecordedFlow(arg1) {
  return window['go']['main']['App']['GetRecordedFlow'](arg1);
}

export function GetRunningCount() {
  return window['go']['main']['App']['GetRunningCount']();
}

export function GetSchedule(arg1) {
  return window['go']['main']['App']['GetSchedule'](arg1);
}

export function GetSupportedStepActions() {
  return window['go']['main']['App']['GetSupportedStepActions']();
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskStats() {
  return window['go']['main']['App']['GetTaskStats']();
}

export function GetVisualDiff(arg1) {
  return window['go']['main']['App']['GetVisualDiff'](arg1);
}

export function ImportFlow(arg1) {
  return window['go']['main']['App']['ImportFlow'](arg1);
}

export function ImportFlowWithWarnings(arg1) {
  return window['go']['main']['App']['ImportFlowWithWarnings'](arg1);
}

export function ImportTask(arg1) {
  return window['go']['main']['App']['ImportTask'](arg1);
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function ListAlertFirings(arg1, arg2) {
  return window['go']['main']['App']['ListAlertFirings'](arg1, arg2);
}

export function ListAlertRules() {
  return window['go']['main']['App']['ListAlertRules']();
}

export function ListBatchGroups() {
  return window['go']['main']['App']['ListBatchGroups']();
}

export function ListCaptchaConfigs() {
  return window['go']['main']['App']['ListCaptchaConfigs']();
}

export function ListDOMSnapshots(arg1) {
  return window['go']['main']['App']['ListDOMSnapshots'](arg1);
}

export function ListProxies() {
  return window['go']['main']['App']['ListProxies']();
}

export function ListProxyCountryStats() {
  return window['go']['main']['App']['ListProxyCountryStats']();
}

export function ListProxyRoutingPresets() {
  return window['go']['main']['App']['ListProxyRoutingPresets']();
}

export function ListRecordedFlows() {
  return window['go']['main']['App']['ListRecordedFlows']();
}

export function ListSchedules() {
  return window['go']['main']['App']['ListSchedules']();
}

export function ListTaskEvents(arg1) {
  return window['go']['main']['App']['ListTaskEvents'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListTasksByBatch(arg1) {
  return window['go']['main']['App']['ListTasksByBatch'](arg1);
}

export function ListTasksByStatus(arg1) {
  return window['go']['main']['App']['ListTasksByStatus'](arg1);
}

export function ListTasksPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListTasksPaginated'](arg1, arg2, arg3, arg4);
}

export function ListVisualBaselines() {
  return window['go']['main']['App']['ListVisualBaselines']();
}

export function ListVisualDiffs(arg1) {
  return window['go']['main']['App']['ListVisualDiffs'](arg1);
}

export function ListVisualDiffsByTask(arg1) {
  return window['go']['main']['App']['ListVisualDiffsByTask'](arg1);
}

export function ListWebSocketLogs(arg1) {
  return window['go']['main']['App']['ListWebSocketLogs'](arg1);
}

export function ParseBatchURLs(arg1, arg2) {
  return window['go']['main']['App']['ParseBatchURLs'](arg1, arg2);
}

export function PauseBatch(arg1) {
  return window['go']['main']['App']['PauseBatch'](arg1);
}

export function PlayRecordedFlow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PlayRecordedFlow'](arg1, arg2, arg3, arg4, arg5);
}

export function PurgeOldData(arg1) {
  return window['go']['main']['App']['PurgeOldData'](arg1);
}

export function ResumeBatch(arg1) {
  return window['go']['main']['App']['ResumeBatch'](arg1);
}

export function RetryFailedBatch(arg1) {
  return window['go']['main']['App']['RetryFailedBatch'](arg1);
}

export function SaveCaptchaConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveCaptchaConfig'](arg1, arg2);
}

export function SaveDOMSnapshot(arg1) {
  return window['go']['main']['App']['SaveDOMSnapshot'](arg1);
}

export function StartAllPending() {
  return window['go']['main']['App']['StartAllPending']();
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function SubmitScheduledTask(arg1, arg2) {
  return window['go']['main']['App']['SubmitScheduledTask'](arg1, arg2);
}

export function TestCaptchaConfig(arg1) {
  return window['go']['main']['App']['TestCaptchaConfig'](arg1);
}

export function ToggleSchedule(arg1, arg2) {
  return window['go']['main']['App']['ToggleSchedule'](arg1, arg2);
}

export function UpdateAlertRule(arg1) {
  return window['go']['main']['App']['UpdateAlertRule'](arg1);
}

export function UpdateRecordedFlow(arg1) {
  return window['go']['main']['App']['UpdateRecordedFlow'](arg1);
}

export function UpdateSchedule(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSchedule'](arg1, arg2, arg3);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3);
}
